apiVersion: v1
kind: Service
metadata:
  name: stackdemo-service
  namespace: dev
  labels:
    app: stackdemo-template
spec:
  type: NodePort
  selector:
    app: stackdemo-template
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30992
